services:
  service1:
    build:
      context: ./service1
    ports:
      - 8199:8199
    expose:
      - 8199
    networks:
      - taskNetwork
  service2:
    build:
      context: ./service2
    ports:
      - 8198:8198
    networks:
      - taskNetwork
    

networks:
  taskNetwork:
    driver: bridge